# Generated by Django 2.1 on 2018-10-14 02:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison
import re


class Migration(migrations.Migration):

    replaces = [('journeylog', '0001_initial'), ('journeylog', '0002_auto_20181014_0546'), ('journeylog', '0003_auto_20181014_0556')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order_no', models.SmallIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('disabled_modules', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            options={
                'ordering': ['order_no', 'date_start'],
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('background', models.CharField(blank=True, max_length=240)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date_start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JourneyLocationVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeylog.Journey')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JourneyMapPointVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeylog.Journey')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('type', models.CharField(choices=[('Buildings', (('ARCADE', 'Arcade hall'), ('CAFE', 'Café'), ('HOTEL', 'Hotel'), ('INFO_CENTER', 'Information center'), ('KARAOKE', 'Karaoke'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('SHOP', 'Shop'))), ('Points of interest', (('MONUMENT', 'Monument'), ('MUSEUM', 'Museum'), ('PARK', 'Park'), ('SHRINE', 'Shrine'))), ('Transit points', (('AIRPORT', 'Airport'), ('BUS_STATION', 'Bus station'), ('RAILWAY_STATION', 'Railway station'), ('SUBWAY_STATION', 'Subway station'))), ('Traveling', (('ONBOARD_AIRPLANE', 'On an airplane'), ('ONBOARD_BUS', 'On a bus'), ('ONBOARD_SHIP', 'On a ship'))), ('Other', (('HOME', 'Home'), ('BUILDING', 'Other building'), ('PLACE', 'Other place')))], default='PLACE', max_length=100)),
                ('color', models.CharField(blank=True, max_length=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeylog.Location')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('filename', models.TextField(editable=False)),
                ('filesize', models.BigIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('hash', models.CharField(editable=False, max_length=40)),
                ('camera_make', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_model', models.CharField(blank=True, max_length=100, null=True)),
                ('focal_length', models.CharField(blank=True, max_length=20, null=True)),
                ('exposure', models.CharField(blank=True, max_length=20, null=True)),
                ('iso_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('f_value', models.CharField(blank=True, max_length=20, null=True)),
                ('flash_fired', models.BooleanField(default=False)),
                ('flash_manual', models.BooleanField(default=False)),
                ('confidentiality', models.SmallIntegerField(default=0)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journeylog.Journey')),
            ],
            options={
                'ordering': ['timestamp', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journeylog.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journeylocationvisit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journeylog.Location'),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeylog.Journey'),
        ),
        migrations.AlterUniqueTogether(
            name='locationname',
            unique_together={('location', 'lang')},
        ),
        migrations.AddField(
            model_name='locationname',
            name='sort_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
