# Generated by Django 2.1 on 2018-10-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0002_auto_20181014_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalpage',
            options={'ordering': ['journey', 'order_no', 'date_start']},
        ),
        migrations.AlterModelOptions(
            name='locationname',
            options={'ordering': ['sort_key', 'location', 'name']},
        ),
    ]
