# Generated by Django 2.1 on 2018-10-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0003_auto_20181016_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='parent_tag',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='journalpage',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_pages', to='journeylog.Journey'),
        ),
        migrations.AlterField(
            model_name='journeylocationvisit',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_visits', to='journeylog.Journey'),
        ),
        migrations.AlterField(
            model_name='journeylocationvisit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='journeylog.Location'),
        ),
        migrations.AlterField(
            model_name='journeymappointvisit',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_point_visits', to='journeylog.Journey'),
        ),
        migrations.AlterField(
            model_name='locationname',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='journeylog.Location'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='journeylog.Journey'),
        ),
    ]
