# Generated by Django 2.1 on 2018-10-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0004_auto_20181016_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(editable=False, max_length=180),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='journeylog.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('journey', 'filename')},
        ),
    ]
