# Generated by Django 2.1 on 2018-12-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0006_journalpage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
