# Generated by Django 2.1 on 2018-12-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0007_auto_20181201_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='background',
            new_name='background_old',
        ),
    ]
