# Generated by Django 2.1 on 2018-12-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0009_journey_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='background_old',
        ),
    ]
