# Generated by Django 2.1 on 2018-12-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0011_auto_20181211_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Buildings', (('ARCADE', 'Arcade hall'), ('BAR', 'Bar'), ('CAFE', 'Café'), ('CHURCH', 'Church'), ('ESCAPE_ROOM', 'Escape room'), ('GAS_STATION', 'Gas station'), ('HOSPITAL', 'Hospital'), ('HOTEL', 'Hotel'), ('INFO_CENTER', 'Information center'), ('KARAOKE', 'Karaoke'), ('MOVIE_THEATER', 'Movie theater'), ('MUSEUM', 'Museum'), ('RESTAURANT', 'Restaurant'), ('SPA', 'Spa'), ('SHOP', 'Shop'), ('THEATER', 'Theater'))), ('Points of interest', (('AMUSEMENT_PARK', 'Amusement park'), ('BEACH', 'Beach'), ('CAMPING', 'Camping grounds'), ('MARKETPLACE', 'Marketplace'), ('MONUMENT', 'Monument'), ('MUSEUM', 'Museum'), ('PARK', 'Park'), ('SHRINE', 'Shrine'), ('SPORTS_CENTER', 'Sports center'), ('ZOO', 'Zoo'))), ('Transit points', (('AIRPORT', 'Airport'), ('BUS_STATION', 'Bus station'), ('RAILWAY_STATION', 'Railway station'), ('SHIP_TERMINAL', 'Ship or ferry terminal'), ('SUBWAY_STATION', 'Subway station'))), ('Traveling', (('ONBOARD_AIRPLANE', 'On an airplane'), ('ONBOARD_BUS', 'On a bus'), ('ONBOARD_SHIP', 'On a ship'), ('ONBOARD_TAXI', 'In a taxi'), ('BICYCLING', 'Riding a bicycle'))), ('Other', (('HOME', 'Home'), ('BUILDING', 'Other building'), ('PLACE', 'Other place')))], default='PLACE', max_length=100),
        ),
    ]
