# Generated by Django 2.1 on 2018-12-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0012_auto_20181223_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpage',
            name='timezone_end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journalpage',
            name='timezone_start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
