# Generated by Django 2.1 on 2019-05-27 13:03

from django.db import migrations, models
import journeylog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0013_auto_20181226_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='languages',
            field=models.CharField(blank=True, help_text='A comma-separated list of locale codes like en_GB.', max_length=200, validators=[journeylog.validators.validate_language_code_list]),
        ),
    ]
