# Generated by Django 2.1 on 2019-05-27 13:27

from django.db import migrations, models
import journeylog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('journeylog', '0014_journey_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='languages',
            field=models.CharField(blank=True, help_text='A comma-separated list of locale codes like en_GB. Use proper casing.', max_length=200, validators=[journeylog.validators.validate_language_code_list]),
        ),
        migrations.AlterField(
            model_name='locationname',
            name='lang',
            field=models.CharField(max_length=10, validators=[journeylog.validators.validate_language_code]),
        ),
    ]
